export const mockUsers = [
  {
    name: 'Bhabasindhu Das',
    email: 'bhabasindhudas621@gmail.com',
    password: 'montagem',
    role: 'admin',
    isVerified: true,
  },
  {
    name: 'Vendor One',
    email: 'vendor@gmail.com',
    password: 'vendor',
    role: 'vendor',
    isVerified: true,
  },
  {
    name: 'John Customer',
    email: 'customer@gmail.com',
    password: 'customer',
    role: 'customer',
    isVerified: true,
  },
];

export const mockCategories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Gadgets, devices, smart appliances, and tech accessories',
    icon: '⚡',
    isActive: true,
  },
  {
    name: 'Fashion & Apparel',
    slug: 'fashion-apparel',
    description: 'Trending clothing, footwear, bags, and luxury accessories',
    icon: '👗',
    isActive: true,
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Furniture, cookware, modern decor, and smart living',
    icon: '🏠',
    isActive: true,
  },
  {
    name: 'Fitness & Sports',
    slug: 'fitness-sports',
    description: 'Workout gear, supplements, outdoor equipment, and sportswear',
    icon: '🏋️',
    isActive: true,
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty-personal-care',
    description: 'Skincare, haircare, grooming essentials, and cosmetics',
    icon: '✨',
    isActive: true,
  },
  {
    name: 'Books & Stationery',
    slug: 'books-stationery',
    description: 'Bestsellers, academic books, notebooks, and office supplies',
    icon: '📚',
    isActive: true,
  },
  {
    name: 'Gaming & Toys',
    slug: 'gaming-toys',
    description: 'Consoles, gaming accessories, collectibles, and board games',
    icon: '🎮',
    isActive: true,
  },
  {
    name: 'Automotive & Tools',
    slug: 'automotive-tools',
    description: 'Car accessories, maintenance tools, and riding gear',
    icon: '🚗',
    isActive: true,
  },
];

export const mockProducts = [
  {
    name: 'Wireless Noise-Canceling Headphones',
    description: 'High-fidelity audio with active noise cancellation and 30-hour battery life.',
    price: 199.99,
    discountPrice: 179.99,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500'],
    isFeatured: true,
    isPublished: true,
  },
  {
    name: 'Minimalist Leather Watch',
    description: 'Classic genuine leather strap with stainless steel casing.',
    price: 120.00,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
    isFeatured: true,
    isPublished: true,
  },
  {
    name: 'Ergonomic Office Chair',
    description: 'Breathable mesh back with adjustable lumbar support and headrest.',
    price: 249.50,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800&auto=format&fit=crop'],
    isFeatured: false,
    isPublished: true,
  },
  {
    name: 'Resistance Bands Set with Handles',
    description: 'Complete workout band set for home training and mobility.',
    price: 29.99,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    isFeatured: true,
    isPublished: true,
  },
  {
    name: 'Organic Vitamin C Hydrating Facial Serum',
    description: 'Rejuvenating skin serum with hyaluronic acid and antioxidants.',
    price: 24.50,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500'],
    isFeatured: false,
    isPublished: true,
  },
  {
    name: 'Mechanical RGB Gaming Keyboard',
    description: 'Tactile switches with customizable per-key backlighting.',
    price: 89.99,
    discountPrice: 74.99,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500'],
    isFeatured: true,
    isPublished: true,
  },
];